export const interests = [
	"Anatomical Pathology",
	"Anesthesiology",
	"Cardiac Surgery",
	"Dermatology",
	"Diagnostic Radiology",
	"Emergency Medicine",
	"Family Medicine",
	"General Pathology",
	"Hematological Pathology",
	"Internal Medicine",
	"Medical Genetics and Genomics",
	"Medical Microbiology",
	"Neurology",
	"Neuropathology",
	"Neurosurgery",
	"Nuclear Medicine",
	"Obstetrics and Gynecology",
	"Ophthalmology",
	"Orthopedic Surgery",
	"Otolaryngology - Head and Neck Surgery",
	"Pediatrics",
	"Physical Medicine and Rehabilitation",
	"Plastic Surgery",
	"Psychiatry",
	"Public Health and Preventive Medicine",
	"Radiation Oncology",
	"Urology",
	"Vascular Surgery",
];